### ISSUE TITLE
Flexible Name Options

### ISSUE THREAD

**Issue by mehtasar** [tehapo/Switch#7]
Is it possible to give function for changing "ON/OFF" title.

For Example:
>Switch switch = new Switch();
>switch.setOnName("Open");
>switch.setOffName("Close");

**Comment by OldIMP** [comment]
Right now a workaround would be to replace the background from org\vaadin\teemu\switchui\public\switch\images\ and overwrite the CSS:
```css
.v-switch-holodeck .v-switch-slider:after {
	content: "OFF";
}
.v-switch-holodeck.on .v-switch-slider:after {
	content: "ON";
}
```
